kotlin.code.style=official
group=io.github.elianfabian
version=1.0.3

POM_NAME=KProxyable
POM_DESCRIPTION=Compile-time Dynamic Proxies for Kotlin Multiplatform.
POM_URL=https://github.com/ElianFabian/KProxyable
POM_INCEPTION_YEAR=2026
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/ElianFabian/KProxyable
POM_SCM_CONNECTION=scm:git:github.com/ElianFabian/KProxyable.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/ElianFabian/KProxyable.git

POM_DEVELOPER_ID=ElianFabian
POM_DEVELOPER_NAME=Elián Fabián
POM_DEVELOPER_EMAIL=elian.fabian.2001@gmail.com

# Modern Sonatype Host for central.sonatype.com
# Used by com.vanniktech.maven.publish
SONATYPE_HOST=CENTRAL_PORTAL
